PRAGMA foreign_keys = ON;

CREATE TABLE SocialMediaSites (
ID INTEGER PRIMARY KEY,
Name TEXT UNIQUE NOT NULL,
Url TEXT  NOT NULL
);

CREATE TABLE Achievements (
ID INTEGER PRIMARY KEY,
Name TEXT NOT NULL,
Description TEXT  NOT NULL
);

CREATE TABLE Metrics (
ID INTEGER PRIMARY KEY,
Name TEXT UNIQUE NOT NULL,
Description TEXT
);

CREATE TABLE Users (
ID INTEGER PRIMARY KEY,
Email TEXT UNIQUE NOT NULL,
PasswordHash TEXT,
Salt TEXT,
FirstName TEXT NOT NULL,
LastName TEXT NOT NULL,
SchoolId INTEGER,
TeamID INTEGER,
JoinDate TEXT,
LastLoginDate TEXT,
IsAdministrator INTEGER
);

CREATE TABLE Schools (
ID INTEGER PRIMARY KEY,
Name TEXT NOT NULL,
Address TEXT,
City TEXT,
ContactId INTEGER
);

CREATE TABLE Teams (
ID INTEGER PRIMARY KEY,
Name TEXT NOT NULL,
CaptainId INTEGER,
Active INTEGER
);

CREATE TABLE Users (
ID INTEGER PRIMARY KEY,
Email TEXT UNIQUE NOT NULL,
FirstName TEXT NOT NULL,
LastName TEXT NOT NULL,
SchoolID INTEGER,
TeamID INTEGER,
JoinDate TEXT,
LastLoginDate TEXT,
IsAdministrator INTEGER,
FOREIGN KEY(SchoolID) REFERENCES Schools(ID),
FOREIGN KEY(TeamID) REFERENCES Teams(ID)
);

CREATE TABLE UserSocialMediaSites (
UserID INTEGER,
SocialMediaSiteId INTEGER,
AccountName TEXT NOT NULL,
FOREIGN KEY(UserID) REFERENCES Users(ID),
FOREIGN KEY(SocialMediaSiteID) REFERENCES SocialMediaSites(ID),
PRIMARY KEY(UserId,SocialMediaSiteID)
);

CREATE TABLE UserAchievements (
AchievementID INTEGER NOT NULL,
UserID INTEGER NOT NULL,
DateEarned TEXT NOT NULL,
FOREIGN KEY(AchievementId) REFERENCES Achievements(ID),
FOREIGN KEY(UserID) REFERENCES Users(ID),
PRIMARY KEY(UserID,AchievementID)
);

CREATE TABLE AchievementSteps (
StepID INTEGER PRIMARY KEY,
AchievementID INTEGER NOT NULL,
StepOrder INTEGER,
Name TEXT NOT NULL,
Description TEXT,
FOREIGN KEY(AchievementID) REFERENCES Achievements(ID)
);

CREATE TABLE UserAchievementSteps (
StepID INTEGER NOT NULL,
UserID INTEGER NOT NULL,
DateEarned TEXT NOT NULL,
FOREIGN KEY(StepID) REFERENCES AchievementSteps(ID),
FOREIGN KEY(UserID) REFERENCES Users(ID),
PRIMARY KEY(UserID,StepID)
);

CREATE TABLE UserRecipes (
Id INTEGER PRIMARY KEY,
UserId INTEGER NOT NULL,
SpoonacularId TEXT NOT NULL,
FOREIGN KEY(UserId) REFERENCES Users(ID)
);

CREATE TABLE UserMetrics (
ID INTEGER PRIMARY KEY,
UserID INTEGER NOT NULL,
MetricID INTEGER NOT NULL,
ActivityTime TEXT NOT NULL,
FOREIGN KEY(MetricID) REFERENCES Metrics(ID),
FOREIGN KEY(UserID) REFERENCES Users(ID)
);

CREATE TABLE FavoriteTypes (
Id INTEGER PRIMARY KEY,
Name TEXT NOT NULL
);

CREATE TABLE UserFavortites (
UserId INTEGER,
SpoonacularId TEXT NOT NULL,
FavoriteTypeID INTEGER NOT NULL,
ActivityTime TEXT NOT NULL,
FOREIGN KEY(UserID) REFERENCES Users(ID),
FOREIGN KEY(FavoriteTypeID) REFERENCES FavoriteTypes(ID),
PRIMARY KEY(UserID,SpoonacularId)
);







